baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'
defaultContentLanguageInSubdir = true
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true

[frontmatter]
  lastmod = ["lastmod", ":git", ":fileModTime", "date"]

[languages]
  [languages."en-US"]
    languageName = 'English'
    languageCode = 'en-US'
    weight = 1
    title = "Tralume Template"

  [languages."zh-Hans"]
    languageName = '简体中文'
    languageCode = 'zh-Hans'
    weight = 2
    title = "Tralume 模板"

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    pageRef = 'home'
    weight = 10
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    pageRef = 'posts'
    weight = 20
  [[menu.main]]
    identifier = 'tags'
    name = 'Tags'
    pageRef = 'tags'
    weight = 30
  [[menu.main]]
    identifier = 'pages'
    name = 'Pages'
    pageRef = 'pages'
    weight = 35
  [[menu.main]]
    identifier = 'friends'
    name = 'Friends'
    pageRef = 'friends'
    weight = 40

[module]
  [[module.imports]]
    path = "forgejo.alexma.top/tralume-org/hugo-theme"
  [module.hugoVersion]
    min = '0.146.0'
    extended = false

[params]
  contentLicense = "arr"
  [params.theme]
    defaultBackgroundProvider = 'pixaroa'
    pixaroaHost = 'https://pixaroa.alexma.top/'

[markup]
  [markup.highlight]
    lineNos = false
    noClasses = false

